### ISSUE TITLE
CI/CD 도입

### ISSUE THREAD

**Issue by hanjo8813** [hanjo8813/SpringBoot-Board#13]
### github actions + docker

https://itcoin.tistory.com/685

### nignx를 통한 무중단 배포

https://stalker5217.netlify.app/devops/github-action-aws-ci-cd-4/

### github actions -> ssh

https://epicarts.tistory.com/160

### docker 환경변수

https://blusky10.tistory.com/404

### slack에 연동

https://gurumee92.github.io/2020/10/github-actions-%EB%8B%AC%EA%B8%B0-slack/

### docker-compose -p
https://meetup.toast.com/posts/277

### docker-compose 환경변수
https://blog.leocat.kr/notes/2021/05/15/docker-use-env-file

**Comment by hanjo8813** [comment]
```yaml
name: Board-API Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          DB_URL : ${{ secrets.DB_URL }}
          DB_USERNAME : ${{ secrets.DB_USERNAME }}
          DB_PASSWORD : ${{ secrets.DB_PASSWORD }}

      # Docker
      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:spring_img .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:spring_img
```
